# Generated by Django 5.1.5 on 2025-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
