# Generated by Django 5.2 on 2025-06-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortener_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortener',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
